### PR TITLE
feat: Updated UnauthorizedAPICalls pattern to pass CIS v1.2.0

### PR DESCRIPTION
**Pull request by dev-slatto**
## Description

According to the documentation of [CIS AWS Foundations Benchmark v1.2.0](https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-cis-controls.html) the pattern for UnauthorizedAPICalls should be `{($.errorCode="*UnauthorizedOperation") || ($.errorCode="AccessDenied*")}`. As of today it also validates the sourceIP and the eventName, leading to the check of CIS 3.1 to fail. 

## Motivation and Context

Merging this change will make the module compliant with the documentation of the [CIS AWS Foundations Benchmark v1.2.0](https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-cis-controls.html).

## Breaking Changes

No breaking changes. Those users that still want to check for sourceIP and eventName can do so by utilising the control_overrides. 

## How Has This Been Tested?
- [x] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [x] I have tested and validated these changes using one or more of the provided `examples/*` projects

- [x] I have executed `pre-commit run -a` on my pull request

### CODE REVIEW

**Comment by dev-slatto** [comment]
Hey @antonbabenko! 👋🏼 
Do you have the time to give this a review? 😄

**Comment by antonbabenko** [comment]
@bryantbiggs Do you have any idea what can be the reason and solution for failing CI runs (e.g. [this](https://github.com/terraform-aws-modules/terraform-aws-cloudwatch/actions/runs/3711803264))?

PS: It is hard to come back from vacation... LOL

**Comment by bryantbiggs** [comment]
Yes, it seems something changed recently on GitHub's side. https://github.com/terraform-aws-modules/terraform-aws-rds/pull/467#discussion_r1059765727

I'll update the workflows today but that PR has the "fix" to avoid this rate limiting

**Comment by antonbabenko** [comment]
@dev-slatto Please update this PR with the change Bryant mentioned and we will be good to go with this PR.

Thank you!

**Comment by dev-slatto** [comment]
Ofc! Done @antonbabenko 😉

**Comment by antonbabenko** [comment]
This PR is included in version 4.1.0 :tada:

**Pull request merged**
