### PR TITLE
feat: Support `aws_cloudwatch_log_data_protection_policy`

### PR DESCRIPTION
**Pull request by magreenbaum**
## Description
Support for `aws_cloudwatch_log_data_protection_policy`.
https://registry.terraform.io/providers/hashicorp/aws/5.56.1/docs/resources/cloudwatch_log_data_protection_policy
https://registry.terraform.io/providers/hashicorp/aws/5.56.1/docs/data-sources/cloudwatch_log_data_protection_policy_document#argument-reference

## Motivation and Context
https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/mask-sensitive-log-data.html

## Breaking Changes
No.

## How Has This Been Tested?
- [x] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [x] I have tested and validated these changes using one or more of the provided `examples/*` projects

- [x] I have executed `pre-commit run -a` on my pull request

### CODE REVIEW

**Comment by magreenbaum** [comment]
Unstale

**Comment by magreenbaum** [comment]
Unstale

**Review by antonbabenko — APPROVED** [review]
Sorry that I skipped this PR for a long time.

**Comment by antonbabenko** [comment]
This PR is included in version 5.6.0 :tada:

**Pull request merged**
